baseURL: "https://martindbx.github.io"
title: Martin Debaisieux
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Notes
          url: notes/
          weight: 2
        - name: Codes
          url: codes/
          weight: 3
        - name: Archive
          url: archive/
          weight: 4

params:
    description: "Website of M. Debaisieux: mathematics & codes"
    author: Martin Debaisieux
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["notes","codes","archive"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Martin Debaisieux
          subtitle: "I am a PhD student supervised by Maja Volkov from the [Mathematics Department](https://web.umons.ac.be/fs-mathematique/en/home/) of the University of Mons. My PhD is funded by the F.R.S.-FNRS. I am interested in arithmetic dynamics, and currently working on Lubin's conjecture using p-adic Hodge theory."
          imageUrl: "profile-picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: John Marston
          buttons:
            - name: Notes
              url: notes/
            - name: Codes
              url: codes/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:martin.debaisieux@umons.ac.be

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Martin Debaisieux"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
